server:
    port: 8088
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force:  true
spring:
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
            
        static-path-pattern: /static/**
        
    datasource:
        #로컬테스트용 경로
        url: jdbc:oracle:thin:@acorndb_high?TNS_ADMIN=C://Users/ejm5/Desktop/project/AcornTeam4/Wallet_AcornDB
        # url: jdbc:oracle:thin:@acorndb_high?TNS_ADMIN=C://Users/TaengOOv/Desktop/WorkPlace/Acorn/Projects/Sixman/source/Wallet_AcornDB
        
        #오라클 클라우드 웹서버용 경로
        # url: jdbc:oracle:thin:@acorndb_high?TNS_ADMIN=/opt/Wallet_AcornDB

        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: sixman
        password: Acornteam4project

mybatis:
    configuration:
        map-underscore-to-camel-case: true

    mapper-locations: /mapper/*Mapper.xml


# server.port=8088

# spring.mvc.view.prefix=/WEB-INF/views/
# spring.mvc.view.suffix=.jsp

# spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
# spring.datasource.url=jdbc:oracle:thin:@acorndb_high?TNS_ADMIN=C://Users/TaengOOv/Desktop/WorkPlace/Acorn/Projects/Sixman/source/Wallet_AcornDB
# spring.datasource.username=sixman
# spring.datasource.password=Acornteam4project

# mybatis.mapper-locations=/mapper/**/*Mapper.xml
# mybatis.configuration.map-underscore-to-camel-case=true

# logging.config=src/main/resources/log4j2.xml


# C:\Users\acorn\Desktop\taengoov\study\repos\Wallet_AcornDB