SELECT 'CP' || TO_CHAR(CURRENT_DATE, 'YYMMDDHHMISS') || LPAD(SEQ_COUPON.NEXTVAL, 5, '0') AS COUPON_ID
FROM DUAL;

SELECT 'OD' || TO_CHAR(CURRENT_DATE, 'YYMMDDHHMISS') || LPAD(SEQ_ORDER.NEXTVAL, 5, '0') AS ORDER_ID
FROM DUAL;

SELECT 'IMG' || TO_CHAR(CURRENT_DATE, 'YYMMDDHHMISS') || LPAD(SEQ_IMAGE.NEXTVAL, 5, '0') AS IMAGE_ID
FROM DUAL;

SELECT 'PD' || TO_CHAR(CURRENT_DATE, 'YYMMDDHHMISS') || LPAD(SEQ_PRODUCT.NEXTVAL, 5, '0') AS PRODUCT_ID
FROM DUAL;